package enums

const (
	POSTGRESQL_DB       = "POSTGRESQL_DB"
	POSTGRESQL_USER     = "POSTGRESQL_USER"
	POSTGRESQL_PASSWORD = "POSTGRESQL_PASSWORD"
	POSTGRESQL_HOST     = "POSTGRESQL_HOST"
	POSTGRESQL_PORT     = "POSTGRESQL_PORT"
	POSTGRESQL_REPLICAS = "POSTGRESQL_REPLICAS"
)
const (
	APP_NAME = "APP_NAME"
	ENV      = "ENV"
	PORT     = "PORT"
	TIMEZONE = "TIMEZONE"
)

const (
	MODE = "MODE"

	SERVER      = "server"
	DEVELOPMENT = "development"
)

const (
	DEV        = "DEV"
	PRODUCTION = "PRODUCTION"
)

const (
	REDIS_SERVER          = "REDIS_SERVER"
	REDIS_MASTER_PASSWORD = "REDIS_MASTER_PASSWORD"
	REDIS_SLAVE_PASSWORD  = "REDIS_SLAVE_PASSWORD"
)

const (
	JWT_SECRET          = "JWT SECRET"
	JWT_ISSUER          = "JWT_ISSUER"
	JWT_EXPIRY_INTERVAL = "JWT_EXPIRY_INTERVAL"

	API_KEY = "API_KEY"
)
