version: "3.9"
services:
  url-shorter:
    build: .
    ports:
      - "80:8000"
  redis:
    image: "redis:alpine"
  db:
    image: postgres:14.1-alpinet
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1
      POSTGRES_DB: url_shortner
      POSTGRES_PORT: 5432

    volumes:
      - db:/var/lib/postgresql/data
      - ./deployments/ddl.sql:/docker-entrypoint-initdb.d/create_tables.sql
volumes:
  db:
    driver: local
